### ISSUE TITLE
Summoned warlock pet disappearing after logout

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#129]
From Project-Aurora created by [Turbowizard1](https://github.com/Turbowizard1): Mike-SPP/Project-Aurora#99

**Comment by sausagemadness** [comment]
Did not describe the issue.

**Comment by acidmanifesto** [comment]
Issue is fixed a while ago. I didnt bother mentioning it here as i didnt have close authority at the time with issues.
