### ISSUE TITLE
[Quest] build-your-barracks [wod garrisons]

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#131]
From Project-Aurora created by [toamuka](https://github.com/toamuka): Mike-SPP/Project-Aurora#101  

https://www.wowhead.com/quest=34461/build-your-barracks

Can't finalize plot for barracks meaning you can't progress in the starting WoD zone.

- Scroll comes back if you run into a different zone and then come back but new players wont find this

**Comment by acidmanifesto** [comment]
Issue is fixed a while ago. I didnt bother mentioning it here as i didnt have close authority at the time with issues.
