### ISSUE TITLE
[Quest] Keeping it Together

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#135]
From Project-Aurora created by [sweetloo32](https://github.com/sweetloo32): Mike-SPP/Project-Aurora#105  

-Major Issue-
https://www.wowhead.com/quest=35176/keeping-it-together
Speaking to Assistant Brightstone doesnt give the option to advance her part of the quest.
She just says "Greetings, Name"
This prevents further progression and testing of alliance garrison's.

**Comment by acidmanifesto** [comment]
Issue is fixed a while ago. I didnt bother mentioning it here as i didnt have close authority at the time with issues.
