### ISSUE TITLE
[Mount] Traveler's Tundra Mammoth doesn't have vendors on if you bought mount from opposite faction character

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#215]
From Project-Aurora created by [Turbowizard1](https://github.com/Turbowizard1): Mike-SPP/Project-Aurora#185  

https://www.wowhead.com/item=44234/reins-of-the-travelers-tundra-mammoth#sold-by

**Comment by acidmanifesto** [comment]
![image](https://user-images.githubusercontent.com/16887899/124185938-9a5b9500-da89-11eb-9bcd-34b463d5f6a5.png)
No issues found currently. However sometimes vendors will not spawn depending on your location.
