### ISSUE TITLE
Hunter's pet vanishes

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#218]
From Project-Aurora created by [Serithul](https://github.com/Serithul): Mike-SPP/Project-Aurora#188  

Report by MamaMaimah

"Hunter pet vanishes between portals and flight paths, now I cannot dismiss him (because I don't have a  current pet) but I cannot summon him either (because I must dismiss current pet)
he just showed up after I've been running around org for 10 minutes so apparently"

He should disappear while flying and reappear after flying by using the flight master.
Pet should appear again after any portal is used

**Comment by acidmanifesto** [comment]
I finally got it fixed to where u can resummon the pet now after it is auto dismissed on map change to a legion zone. No need to relog anymore. Patch will be sent into aurora shortly. This was a day zero bug i been trying to figure out for about year. Thank you for your patience and report.
