### ISSUE TITLE
[Hunter Classhall] You die when you use Great Eagle to go anywhere

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#228]
From Project-Aurora created by [BsouzaM](https://github.com/BsouzaM): Mike-SPP/Project-Aurora#198  

![image](https://user-images.githubusercontent.com/41747947/93668876-8bba6900-fa87-11ea-9ad0-f5db5c70ba16.png)

**Comment by acidmanifesto** [comment]
I am not having it happen. However, minimal or select clients that were download have incomplete data and will result in player's death. At this time I can not replicate it at all.
