### ISSUE TITLE
[Allied Races/Horde] The quest "A Choice of Allies" isn't working.

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#229]
From Project-Aurora created by [BsouzaM](https://github.com/BsouzaM): Mike-SPP/Project-Aurora#199  

![LS_Client_64_bit_xwmYPfzFgz](https://user-images.githubusercontent.com/41747947/93672373-40fa1a80-faa2-11ea-9b06-b9210f30f924.png)
![image](https://user-images.githubusercontent.com/41747947/93672363-350e5880-faa2-11ea-9fb6-00dffcf21b48.png)

**Comment by acidmanifesto** [comment]
Quest does work. U need to meet the requirements of the allied races campaign as it was in retail and every other pserver.
