### ISSUE TITLE
[Battle Pet Trainer] No Battle Pet Trainers can train you how to fight using pets.

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#230]
From Project-Aurora created by [BsouzaM](https://github.com/BsouzaM): Mike-SPP/Project-Aurora#200  

![image](https://user-images.githubusercontent.com/41747947/93672417-97ffef80-faa2-11ea-8d9b-4430c1999903.png)
![image](https://user-images.githubusercontent.com/41747947/93672419-9df5d080-faa2-11ea-8988-f949774c2295.png)

**Comment by acidmanifesto** [comment]
This is gonna be a easy one if we get list of pet trainers missing the skill it can be added in quickly

**Comment by acidmanifesto** [comment]
Full Audit completed for both Alliance and Horde Pet trainers. Found a total of 10 out 22 that were messed up or incorrect. Patch has been sent in.
