### ISSUE TITLE
[Battle Pets] Tyrael's Hilt

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#239]
From Project-Aurora created by [GarzoxShaw](https://github.com/GarzoxShaw): Mike-SPP/Project-Aurora#209  

This pet can be buy at the Battle Shop category Pet : Tyrael's Hilt for 30 battle coins

After using the Tyrael's Hilt item, you get the achievement, the game count one more pet in your collection (the number of total pet you have) but the pet doesnt exist in the collection itself, so he can't see and summon the pet
![image](https://user-images.githubusercontent.com/71578432/93797622-c31e4680-fc3c-11ea-8ae6-147ed5565d09.png)
![image](https://user-images.githubusercontent.com/71578432/93797631-c580a080-fc3c-11ea-8246-164a25242086.png)

**Comment by sausagemadness** [comment]
Its Fixed Close please

**Comment by Duff-SPP** [comment]
Fixed
