### ISSUE TITLE
[Battle Shop] The Pet Category

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#241]
From Project-Aurora created by [GarzoxShaw](https://github.com/GarzoxShaw): Mike-SPP/Project-Aurora#211  

This is a list of the pet having issue (with detail) : 

-Treasure Goblin's Pack : Does not appear in collection
![image](https://user-images.githubusercontent.com/71578432/93816134-63816480-fc57-11ea-9ee7-5b71b4f5470c.png)

-Baby Shark : Does not appear in collection
![image](https://user-images.githubusercontent.com/71578432/93816722-31243700-fc58-11ea-866d-6f737339ffe5.png)

-Murkimus' Tiny Spear : there is a another called "Murkimus' Little Spear" i can't use this one because i already used the Little one
![image](https://user-images.githubusercontent.com/71578432/93817082-b4458d00-fc58-11ea-8958-5f650559ca90.png)

-Tyrael's Hilt : Does not appear in collection
![image](https://user-images.githubusercontent.com/71578432/93817218-eb1ba300-fc58-11ea-8757-24d3521ba605.png)

This one was in pet category, it's a mount, MDic already fix that for the next patch
![image](https://user-images.githubusercontent.com/71578432/93817349-1e5e3200-fc59-11ea-9c14-0167b8d1ee10.png)

Pet below get learned but didnt consumed the item

![image](https://user-images.githubusercontent.com/71578432/93817491-5b2a2900-fc59-11ea-9a4f-5a4f8f271abd.png)
![image](https://user-images.githubusercontent.com/71578432/93817543-6da46280-fc59-11ea-894c-0d785686e18c.png)
![image](https://user-images.githubusercontent.com/71578432/93817566-75640700-fc59-11ea-810e-c990eafbe066.png)
![image](https://user-images.githubusercontent.com/71578432/93817609-7f860580-fc59-11ea-91ad-d82e17ae5ae7.png)
![image](https://user-images.githubusercontent.com/71578432/93817647-8b71c780-fc59-11ea-9ba6-4cf112f40312.png)
![image](https://user-images.githubusercontent.com/71578432/93817681-94629900-fc59-11ea-9063-510b180badfb.png)
![image](https://user-images.githubusercontent.com/71578432/93817717-9f1d2e00-fc59-11ea-9307-752644ac07af.png)

**Comment by acidmanifesto** [comment]
This was fixed a while ago and i forgot to close it.
