### ISSUE TITLE
[Garrison] NPC Missing for quest

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#245]
From Project-Aurora created by [GarzoxShaw](https://github.com/GarzoxShaw): Mike-SPP/Project-Aurora#215  

NPC i need to talk to complete my quest is not here (Tried to relog to solve but it's a failure)
I am not able to complete my quest and continue Garrison questline

![image](https://user-images.githubusercontent.com/71578432/93929535-4e223e00-fd1c-11ea-9a9b-e7952ea3db3f.png)
![image](https://user-images.githubusercontent.com/71578432/93929547-4fec0180-fd1c-11ea-83e1-493531a7415a.png)
![image](https://user-images.githubusercontent.com/71578432/93929554-524e5b80-fd1c-11ea-999a-44472d55d955.png)

**Comment by acidmanifesto** [comment]
Issue is fixed a while ago. I didnt bother mentioning it here as i didnt have close authority at the time with issues.
