### ISSUE TITLE
[Garrison] NPC Missing for quest 2

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#246]
From Project-Aurora created by [GarzoxShaw](https://github.com/GarzoxShaw): Mike-SPP/Project-Aurora#216  

Same bug as the previous report

![image](https://user-images.githubusercontent.com/71578432/93933392-e4a52e00-fd21-11ea-805a-d4fa4027e8b7.png)
![image](https://user-images.githubusercontent.com/71578432/93933433-f38be080-fd21-11ea-8cc0-649cf87089f0.png)
![image](https://user-images.githubusercontent.com/71578432/93933468-02729300-fd22-11ea-9bd2-f4e5b94a7d9e.png)

**Comment by sausagemadness** [comment]
This NPC is not missing, she are here with a garrison level 1 and i have a level 2

The main problem is because i shouldnt not be able to make my garrison level 2 before completing this quest. even the minimap say you should be in level 1

**Comment by acidmanifesto** [comment]
Issue is fixed a while ago. I didnt bother mentioning it here as i didnt have close authority at the time with issues.
