### ISSUE TITLE
[Quest] Den of Wolves

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#247]
From Project-Aurora created by [sausagemadness](https://github.com/sausagemadness): Mike-SPP/Project-Aurora#217  

Farseer Drek Thar will give the quest in the garrison, but he is no where to be found on the garrison.

Image:
![image](https://user-images.githubusercontent.com/71482732/93985412-ac91ff80-fda2-11ea-9c2b-e2266331fbb3.png)

Wowhead Link:
https://www.wowhead.com/quest=34379/den-of-wolves

Youtube link:
https://youtu.be/8V74uv4J5mA?t=1297

**Comment by acidmanifesto** [comment]
Issue is fixed a while ago. I didnt bother mentioning it here as i didnt have close authority at the time with issues.
