### ISSUE TITLE
[Battle Shop] Toy's 

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#261]
From Project-Aurora created by [GarzoxShaw](https://github.com/GarzoxShaw): Mike-SPP/Project-Aurora#231  

I did a check of every toy's of the battle shop, some didnt wanted to be casted because of my choice of zone to to this (but i checked everything and all worked)

i have noticed two toy's not working correctly or just not usable for me

![image](https://user-images.githubusercontent.com/71578432/94748368-6f6cd500-0381-11eb-8d86-8c229ee65ad6.png)
![image](https://user-images.githubusercontent.com/71578432/94748337-5a904180-0381-11eb-8bbe-84a4c47c49e6.png)
![image](https://user-images.githubusercontent.com/71578432/94748340-5c5a0500-0381-11eb-8334-4a3b87ce5929.png)

**Comment by acidmanifesto** [comment]
The item works but can not be used by the opposite faction for the dark spear toy. The mana mini bomb is horde only.
