### ISSUE TITLE
SPP Token deal damage

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#266]
From Project-Aurora created by [GarzoxShaw](https://github.com/GarzoxShaw): Mike-SPP/Project-Aurora#236  

I wanted to see firework so i got and used 19 SPP Token (the one give Battle coin yeah) and it almost killed me
Firework effect do damage only on the player using token, and can kil him if he use too much token

https://i.gyazo.com/753fdd643b3fc92f663923056b85dd6c.mp4
![image](https://user-images.githubusercontent.com/71578432/95027718-edd7b880-069a-11eb-8508-2d206391943e.png)

**Comment by acidmanifesto** [comment]
As intended. Part of the visual explosion that is apart of the designed.
