### ISSUE TITLE
[Quest] Uniting the Isles

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#36]
From Project-Aurora created by [Spydoc](https://github.com/Spydoc): Mike-SPP/Project-Aurora#6  

Major issue:

The quest Uniting the Isles is completeable without meeting the criteria of being at least friendly with the factions in the 5 Broken Isles zones. Because of this you can unlock the world quests without having to grind any reputation.

https://www.wowhead.com/quest=43341/uniting-the-isles

**Comment by Duff-SPP** [comment]
Pretty sure the quest have been Flagged as auto complete since its bugged..

re-Open if im wrong
