### ISSUE TITLE
[NPC] Colerian, Alteria and Selenyi

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#39]
From Project-Aurora created by [Spydoc](https://github.com/Spydoc): Mike-SPP/Project-Aurora#9  

Minor issue:

The three NPCs for the world quest DANGER: Colerian, Alteria, and Selenyi aren't patrolling, they're just standing in one place.

https://www.wowhead.com/quest=41697/danger-colerian-alteria-and-selenyi

**Comment by acidmanifesto** [comment]
patch sent in.

**Comment by Serithul** [comment]
Fix is live. Let us know if there's a problem with it.
