### ISSUE TITLE
[Quest] Bareback Brawl

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#41]
From Project-Aurora created by [Spydoc](https://github.com/Spydoc): Mike-SPP/Project-Aurora#11  

Major issue:

The world quest Bareback Brawl is currently uncompleteable. Slaying a beast (more specifically reducing its health low enough in order for it to become friendly) should give 5% towards the progress of the quest and killing a player should give 15%. At the moment you don't gain any progress by defeating the mobs, although I haven't tested if killing a player would give you credit. Also if you switch to a different beast before dismounting the previous one, you'll have the ability of the new beast but the beast itself won't be visible.

https://www.wowhead.com/quest=42025/bareback-brawl

**Comment by skeezerbean** [comment]
Most seems fixed already
Stormtalon removed as being a trigger NPC, set to enable flying. Can be closed.
