### ISSUE TITLE
[NPC] Helmouth Raiders

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#42]
From Project-Aurora created by [Spydoc](https://github.com/Spydoc): Mike-SPP/Project-Aurora#12  

Major issue:

The rares Helmouth Raiders don't seem to have the correct loot table. They pretty much dropped nothing and they should drop things that other rares are dropping like artifact power tokens.

https://www.wowhead.com/npc=92703/helmouth-raider

**Comment by Duff-SPP** [comment]
Order Resource Drop Added to lootTable. Please DM Me about more drops since there is no info to find on its drops
