### ISSUE TITLE
[Quest] Their Dying Breaths

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#45]
From Project-Aurora created by [Spydoc](https://github.com/Spydoc): Mike-SPP/Project-Aurora#15  

Major issue:

The quest Their Dying Breaths is uncompleteable. After reviving 4 whelps, another whelp should appear that you also need to revive but it never actually appears. The mobs in the area, which aren't even supposed to be there in the first place, are killing the whelps. I'm sure that this issue is related to the huge phasing problems in the area but because the quest is uncompleteable, I believe that it's worth reporting it separately.

https://www.wowhead.com/quest=42271/their-dying-breaths

**Comment by skeezerbean** [comment]
Sending a fix to MDic for this, can be closed
