### ISSUE TITLE
[NPC] Redcrested Heron

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#59]
From Project-Aurora created by [Spydoc](https://github.com/Spydoc): Mike-SPP/Project-Aurora#29  

Minor issue:

Hovering over the Redcrested Heron mob shows a cogwheel cursor instead of a sword one, making it unable to attack it by right-clicking. Once you start attacking with an ability, the cursor becomes a sword one.

https://www.wowhead.com/npc=105838/redcrested-heron

**Comment by acidmanifesto** [comment]
Patch sent in.

**Comment by Serithul** [comment]
Fix is live. Let us know if there's a problem with it.
