### ISSUE TITLE
[NPC] Jade Darkhaven

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#76]
From Project-Aurora created by [Spydoc](https://github.com/Spydoc): Mike-SPP/Project-Aurora#46  

Major issue:

I believe the rare elite Jade Darkhaven is missing because not only that the elite can't be found but also there are no mobs in the tower that she's supposed to be occupying and around it as well. She usually stands in a tower that's very similar to the one that Lysanis Shadesoul is occupying but that one has the necessary mobs spawned.

https://www.wowhead.com/npc=103975/jade-darkhaven

**Comment by acidmanifesto** [comment]
patch has been sent in

**Comment by Serithul** [comment]
Fix is live. Let us know if there's a problem with it.
