### ISSUE TITLE
[NPC] Portal Keeper V'thaal

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#80]
From Project-Aurora created by [Spydoc](https://github.com/Spydoc): Mike-SPP/Project-Aurora#50  

Medium issue:

The elite Portal Keeper V'thaal is missing all of its abilities.

https://www.wowhead.com/npc=117647/portal-keeper-vthaal#abilities

**Comment by acidmanifesto** [comment]
Patch has been sent in

**Comment by Serithul** [comment]
Fix is live. Let us know if there's a problem with it.
