### ISSUE TITLE
[NPC] Coura, Mistress of Arcana

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#81]
From Project-Aurora created by [Spydoc](https://github.com/Spydoc): Mike-SPP/Project-Aurora#51  

Major issue:

To my knowledge the rare Coura, Mistress of Arcana is unreachable. There's a gate that's blocking the entrance to her room and from all the sources that I've checked, there shouldn't be a gate in the first place.

https://www.wowhead.com/npc=108255/coura-mistress-of-arcana

**Comment by acidmanifesto** [comment]
patch has been sent in

**Comment by Serithul** [comment]
Fix is live. Let us know if there's a problem with it.
