### ISSUE TITLE
[NPC] Brawlgoth

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#84]
From Project-Aurora created by [Spydoc](https://github.com/Spydoc): Mike-SPP/Project-Aurora#54  

Medium issue:

The rare Brawlgoth doesn't use one of his abilities. He should be using the ability Grinding Crunch which grabs you, making you unable to use any skills while grabbed and dealing periodic damage until you get released a couple of seconds later.

https://www.wowhead.com/npc=107127/brawlgoth#abilities

**Comment by acidmanifesto** [comment]
patch has been sent in

**Comment by Serithul** [comment]
Fix is live. Let us know if there's a problem with it.
