### ISSUE TITLE
[NPC] Flog the Captain-Eater

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#89]
From Project-Aurora created by [Spydoc](https://github.com/Spydoc): Mike-SPP/Project-Aurora#59  

Medium issue:

The problems are regarding the rare elite Flog the Captain-Eater. Normally when he's out of combat, he's channeling the Anchor Drag ability, which is normal. The issue is that when you engage the rare, he continues to channel it, meaning that he doesn't attack you. After I ran out of range to reset him, I immediatelly pulled him again before he had the chance to start channeling Anchor Drag again and the second time he started attacking but without using any of his actual abilities, so I'm assuming they're missing.

https://www.wowhead.com/npc=89884/flog-the-captain-eater#abilities

**Comment by acidmanifesto** [comment]
patch sent in

**Comment by Serithul** [comment]
Fix is live. Let us know if there's a problem with it.
