### ISSUE TITLE
[NPC] Stroxis, Horux and Zorux

### ISSUE THREAD

**Issue by sausagemadness** [Project-AuroraWoW/Project-Aurora#91]
From Project-Aurora created by [Spydoc](https://github.com/Spydoc): Mike-SPP/Project-Aurora#61  

Medium issue:

The rare Houndmaster Stroxis should be accompanied by Horux and Zorux the whole time. Currently they're not spawned.

https://www.wowhead.com/npc=107136/houndmaster-stroxis
https://www.wowhead.com/npc=107169/horux
https://www.wowhead.com/npc=107170/zorux

**Comment by acidmanifesto** [comment]
patch has been sent in

**Comment by Serithul** [comment]
Fix is live. Let us know if there's a problem with it.
